#!/bin/bash

all_handlers=()

for home in `getent passwd | cut -d: -f6`; do
  [ -d $home/.mozilla/firefox ] && all_handlers+=(`find $home/.mozilla/firefox -maxdepth 2 -type f -regextype grep -regex "$home/\.mozilla/firefox/[a-z0-9]\{8\}\.default[^/\\]*/handlers.json$"`)
done

if [ ${#all_handlers[*]} -eq 0 ]; then
  exit 0
fi

for handlers in ${all_handlers[@]}; do
  #echo $handlers
  content=`jq -c '.schemes .bigrats={action:2,handlers:[null]}' $handlers`
  #echo $content
  echo $content > $handlers
done
